<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<OutputType>WinExe</OutputType>
	<TargetFramework>net8.0-windows</TargetFramework>
	<RuntimeIdentifiers>win-x86</RuntimeIdentifiers>
	<RootNamespace>LdapCloudSync.ConfigLauncher</RootNamespace>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
	<AssemblyName>ConNexus.ConfigLauncher</AssemblyName>
	<Title>ConNexus.ConfigLauncher</Title>
	<Product>ConNexus</Product>
  </PropertyGroup>

  <ItemGroup>
	<ProjectReference Include="..\LdapCloudSync.App\LdapCloudSync.App.csproj" />
  </ItemGroup>

</Project>
