<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<OutputType>WinExe</OutputType>
	<TargetFramework>net8.0-windows</TargetFramework>
	<RootNamespace>LdapCloudSync.ConfigLauncher</RootNamespace>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
	<AssemblyName>LdapCloudSync.ConfigLauncher</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
	<ProjectReference Include="..\LdapCloudSync.App\LdapCloudSync.App.csproj" />
  </ItemGroup>

</Project>
