<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>LdapCloudSync.App</RootNamespace>
    <AssemblyName>ConNexus</AssemblyName>
    <Title>ConNexus</Title>
    <Product>ConNexus</Product>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Connexus.ico</ApplicationIcon>
	<Version>1.0.1</Version>
	<AssemblyVersion>1.0.1.0</AssemblyVersion>
	<FileVersion>1.0.1.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="Connexus.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LdapCloudSync.Core\LdapCloudSync.Core.csproj" />
  </ItemGroup>

</Project>